- Cari Measure of Central Tendency dari data tersebut.
- Cari Measure of Variance dari data tersebut.

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('covid_19_indonesia_time_series_all.csv')
print(df)

            Date Location ISO Code          Location  New Cases  New Deaths  \
0       3/1/2020             ID-JK       DKI Jakarta          2           0
1       3/2/2020             ID-JK       DKI Jakarta          2           0
2       3/2/2020               IDN         Indonesia          2           0
3       3/2/2020             ID-RI              Riau          1           0
4       3/3/2020             ID-JK       DKI Jakarta          2           0
...          ...               ...               ...        ...         ...
31817  9/15/2022             ID-SA    Sulawesi Utara         37           0
31818  9/15/2022             ID-SB    Sumatera Barat         13           0
31819  9/15/2022             ID-SS  Sumatera Selatan         16           0
31820  9/15/2022             ID-SU    Sumatera Utara         50           0
31821  9/16/2022               IDN         Indonesia       2358          27

       New Recovered  New Active Cases  Total Cases  Total Deaths  \
0                  0                 2           39            20
1                  0                 2           41            20
2                  0                 2            2             0
3                  0                 1            1             0
4                  0                 2           43            20
...              ...               ...          ...           ...
31817              0                37        52770          1213
31818              3                10       104640          2371
31819              1                15        82198          3376
31820              5                45       158866          3288
31821           2997              -666      6405044        157876

       Total Recovered  ...  Latitude New Cases per Million  \
0                   75  ... -6.204699                  0.18
1                   75  ... -6.204699                  0.18
2                    0  ... -0.789275                  0.01
3                    1  ...  0.511648                  0.16
4                   75  ... -6.204699                  0.18
...                ...  ...       ...                   ...
31817            50997  ...  1.259638                 14.01
31818           102066  ... -0.850253                  2.36
31819            78510  ... -3.216212                  1.95
31820           154924  ...  2.191894                  3.36
31821          6218708  ... -0.789275                  8.89

       Total Cases per Million New Deaths per Million  \
0                         3.60                    0.0
1                         3.78                    0.0
2                         0.01                    0.0
3                         0.16                    0.0
4                         3.96                    0.0
...                        ...                    ...
31817                 19974.38                    0.0
31818                 18959.11                    0.0
31819                 10002.74                    0.0
31820                 10680.15                    0.0
31821                 24153.07                    0.1

      Total Deaths per Million Total Deaths per 100rb Case Fatality Rate  \
0                         1.84                   0.18             51.28%
1                         1.84                   0.18             48.78%
2                         0.00                   0.00              0.00%
3                         0.00                   0.00              0.00%
4                         1.84                   0.18             46.51%
...                        ...                    ...                ...
31817                   459.14                  45.91              2.30%
31818                   429.59                  42.96              2.27%
31819                   410.83                  41.08              4.11%
31820                   221.04                  22.10              2.07%
31821                   595.34                  59.53              2.46%

      Case Recovered Rate Growth Factor of New Cases  \
0                 192.31%                        NaN
1                 182.93%                       1.00
2                   0.00%                        NaN
3                 100.00%                        NaN
4                 174.42%                       1.00
...                   ...                        ...
31817              96.64%                       2.85
31818              97.54%                       6.50
31819              95.51%                       3.20
31820              97.52%                       1.92
31821              97.09%                       0.89

       Growth Factor of New Deaths
0                              NaN
1                             1.00
2                              NaN
3                              NaN
4                             1.00
...                            ...
31817                         1.00
31818                         1.00
31819                         1.00
31820                         1.00
31821                         1.29

[31822 rows x 38 columns]

Finding the mean:

In [6]:
print (df['New Cases'].mean())
print (df['New Deaths'].mean())
print (df['New Recovered'].mean())
print (df['New Active Cases'].mean())
print (df['Total Cases'].mean())
print (df['Total Deaths'].mean())

402.311388347684
9.920652378857394
390.39849789453837
1.9922380742882282
159449.99770598958
4564.753221042047

Finding the median:

In [9]:
df.sort_values('New Cases')
df.sort_values('New Deaths')
df.sort_values('New Recovered')
df.sort_values('New Active Cases')
df.sort_values('Total Cases')
df.sort_values('Total Deaths')

df

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.00,1.00
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31817,9/15/2022,ID-SA,Sulawesi Utara,37,0,0,37,52770,1213,50997,...,1.259638,14.01,19974.38,0.0,459.14,45.91,2.30%,96.64%,2.85,1.00
31818,9/15/2022,ID-SB,Sumatera Barat,13,0,3,10,104640,2371,102066,...,-0.850253,2.36,18959.11,0.0,429.59,42.96,2.27%,97.54%,6.50,1.00
31819,9/15/2022,ID-SS,Sumatera Selatan,16,0,1,15,82198,3376,78510,...,-3.216212,1.95,10002.74,0.0,410.83,41.08,4.11%,95.51%,3.20,1.00
31820,9/15/2022,ID-SU,Sumatera Utara,50,0,5,45,158866,3288,154924,...,2.191894,3.36,10680.15,0.0,221.04,22.10,2.07%,97.52%,1.92,1.00
31821,9/16/2022,IDN,Indonesia,2358,27,2997,-666,6405044,157876,6218708,...,-0.789275,8.89,24153.07,0.1,595.34,59.53,2.46%,97.09%,0.89,1.29

In [10]:
print (df['New Cases'].median())
print (df['New Deaths'].median())
print (df['New Recovered'].median())
print (df['New Active Cases'].median())
print (df['Total Cases'].median())
print (df['Total Deaths'].median())

27.0
0.0
20.0
0.0
23596.5
565.5

Finding the mode:

In [11]:
print (df['New Cases'].mode())
print (df['New Deaths'].mode())
print (df['New Recovered'].mode())
print (df['New Active Cases'].mode())
print (df['Total Cases'].mode())
print (df['Total Deaths'].mode())

0    0
Name: New Cases, dtype: int64
0    0
Name: New Deaths, dtype: int64
0    0
Name: New Recovered, dtype: int64
0    0
Name: New Active Cases, dtype: int64
0    1
Name: Total Cases, dtype: int64
0    1
Name: Total Deaths, dtype: int64

In [14]:
numcols = ['New Cases', 'New Deaths', 'New Recovered', 'New Active Cases' ,'Total Cases', 'Total Deaths']
for col in numcols:
    print(df[col].name + ' range: ' + str(df[col].max() - df[col].min()))

New Cases range: 64718
New Deaths range: 2069
New Recovered range: 61361
New Active Cases range: 69103
Total Cases range: 6405043
Total Deaths range: 157876

In [16]:
print (df['New Cases'].var())
print (df['New Deaths'].var())
print (df['New Recovered'].var())
print (df['New Active Cases'].var())
print (df['Total Cases'].var())
print (df['Total Deaths'].var())

5385322.845713514
4113.82152186457
4839466.74440211
1487212.8220068526
392431396999.77057
313068129.77232254